name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install core dependencies
        run: cd axon-generator-toolbox/core && npm i

      - name: Install gui dependencies
        run: cd axon-generator-toolbox/gui && npm i

      - name: Build the project
        run: cd axon-generator-toolbox/gui && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./axon-generator-toolbox/gui/build
