name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install core dependencies
        run: cd white-matter-generator/core && npm i

      - name: Install gui dependencies
        run: cd white-matter-generator/gui && npm i

      - name: Build the project
        run: cd white-matter-generator/gui && npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./white-matter-generator/gui/build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
